<?php

namespace Pharmacie\ProduitBundle\Repository;

/**
 * ProduitCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}