<?php
/**
 * Created by Jean Nica RALAVA.
 * User: jralava
 * Date: 3/11/2018
 * Time: 3:53 PM
 */

namespace Pharmacie\ProduitBundle\Repository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{

}