<?php

namespace Pharmacie\PersonnageBundle\Repository;

/**
 * AssurancesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssurancesRepository extends \Doctrine\ORM\EntityRepository
{
}
