<?php

namespace Pharmacie\PersonnageBundle\Repository;

/**
 * SexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SexeRepository extends \Doctrine\ORM\EntityRepository
{
}
